- type: replace
  path: /addons/-
  value:
    name: loggr-system-metrics-agent
    include:
      stemcell:
      - os: ubuntu-trusty
      - os: ubuntu-xenial
    exclude:
      jobs:
      - name: smoke_tests
        release: cf-smoke-tests
    jobs:
    - name: loggr-system-metrics-agent
      release: loggregator-agent
      properties:
        log_agent:
          ca_cert: "((loggregator_ca.certificate))"
          client_cert: "((system_metrics_agent.certificate))"
          client_key: "((system_metrics_agent.private_key))"

- type: replace
  path: /variables/-
  value:
    name: system_metrics_agent
    type: certificate
    options:
      ca: loggregator_ca
      common_name: forwarder-agent
      extended_key_usage:
      - client_auth

