golang-1.25-linux/1e4dadb8a796a20044e177a108eec65780cd59c308da84f7fdbfdbc758cdf312:
  size: 59768009
  object_id: 37335eb8-8dcb-413e-580e-03c0f67bf67d
  sha: sha256:9e9b755d63b36acf30c12a9a3fc379243714c1c6d3dd72861da637f336ebb35b
golang-1.25-windows/fb4cf863311cceb62a13615813687871d16e7d71f93817ec7b533d6d569e7880:
  size: 67442664
  object_id: 85fd0767-364d-4eee-40a3-d127028d2504
  sha: sha256:ae756cce1cb80c819b4fe01b0353807178f532211b47f72d7fa77949de054ebb
