name: unit-tests
on:
  pull_request:
    branches:
    - main
    - v3.21.x
    - v6.0.x
  push:
    branches:
    - main
    - v3.21.x
    - v6.0.x
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go vet ./...
        working-directory: src
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go test -v -race ./...
        working-directory: src
