dist:
  module: code.cloudfoundry.org/loggregator-agent-release/src/otel-collector
  name: cf-otel-collector
  description: Cloud Foundry OpenTelemetry Collector
  otelcol_version: 0.102.1
  output_path: otel-collector
  version: 7.7.7
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.102.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.102.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.102.0
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.102.1
